version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: language_learning_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: language_learning_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - app_network

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: language_learning_crawler
    volumes:
      - ./crawler:/app
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge 